# 08/04

## Transpose: Be careful with your data. 

Rule of thumb: You can only use transpose when both of your matricies store data as rows. 

Q: Why is this? Experiment. 


## Matrix Transpose 

There is a difference between reshape and transpose. 

What is that difference? 

## transpose() / T in np. 





In [1]:
import numpy as np

In [7]:
inputs = np.array([[-0.27, 0.75, 0.64, 0.41]])

print("Inputs: ", inputs, "\n")
print("Inputs Shape: " , inputs.shape, "\n")


weights = np.array([[0.02, 0.001, -0.03, 0.036],
                    [0.04, -0.003, 0.025, 0.009],
                    [0.012, -0.045, 0.28, -0.067]])

print("Weights: ", weights, "\n")

print("Weights Shape: ", weights.shape)


Inputs:  [[-0.27  0.75  0.64  0.41]] 

Inputs Shape:  (1, 4) 

Weights:  [[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]] 

Weights Shape:  (3, 4)


In [8]:
np.matmul(inputs, weights)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [9]:
# However, when we transpose the inputs matrix. 

np.matmul(weights, inputs.T)

array([[-0.00909],
       [ 0.00664],
       [ 0.11474]])

## Lesson 2 Intro to Neural Networks (Neural Networks) - Visualizing the AND logical operator as a binary table, and then plotting the coordinates on a graph. You can now visualize the data in this manner. 


Nerual networks then, utilize the encoding of data into numerical value points, which then learning can be imposed upon. 

How does this work in a larger system with more complex architecture? Its all encoding and processing. 

For example: 

You have a test score (which is an arbitrary start point)... you could analyse this process as well. 

Test score encoded with GPA. This is then arbitraily related on a coordinate system. This relation can be represented in a matrix. Now, if there is enough of these relations with consistant representation, then you have something. It becomes real. This relationship is created, and is not longer arbitrary. 

Test x GPA x Person matrix. 


In [17]:
person = np.array([[[1], [3.5]],
                   [[2], [3.0]]])

print("Person Shape:", person.shape)
person


Person Shape: (2, 2, 1)


array([[[ 1. ],
        [ 3.5]],

       [[ 2. ],
        [ 3. ]]])

In [ ]:
import matplotlib.pyplot as plt

